# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 5.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-10-03 04:15-0400\n"
"PO-Revision-Date: 2017-10-03 04:15-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.1\n"
"Language: en_US\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;"

#: nova_powervm/virt/powervm/driver.py:211
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Ожидался только один хост; обнаружено: %d"

#: nova_powervm/virt/powervm/driver.py:1002
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Подключение vif не выполнено, поскольку экземпляр %s не найден."

#: nova_powervm/virt/powervm/driver.py:1007
msgid "Plug vif failed because of an unexpected error."
msgstr "Подключение vif не выполнено вследствие непредвиденной ошибки."

#: nova_powervm/virt/powervm/driver.py:1097
msgid "Cannot reduce disk size."
msgstr "Невозможно уменьшить размер диска."

#: nova_powervm/virt/powervm/driver.py:1111
#: nova_powervm/virt/powervm/driver.py:1219
msgid "Cannot migrate local disks."
msgstr "Невозможно выполнить миграцию локальных дисков."

#: nova_powervm/virt/powervm/driver.py:1740
msgid "Unable to open console."
msgstr "Не удалось открыть консоль."

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual optical "
"media within.  Unable to create the media repository."
msgstr ""
"Не удалось найти группу томов %(vol_grp)s для размещения виртуального "
"оптического носителя.  Не удалось создать хранилище носителей."

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with UDID "
"%(udid)s failed to appear after %(polls)d polls over %(timeout)d seconds."
msgstr ""
"При проверке шины SCSI %(bus)x в разделе управления диск с UDID "
"%(udid)s не ответил ни на один из %(polls)d опросов в течение %(timeout)d с."

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"Ожидался ровно один диск в разделе управления "
"%(path_pattern)s; обнаружено %(count)d."

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d seconds."
msgstr ""
"Устройство %(devpath)s по-прежнему присутствует в разделе управления после "
"попытки удалить его.  Опрошено %(polls)d раз за %(timeout)d с."

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"Не удалось подключить загрузочный диск экземпляра %(instance_name)s к разделу "
"управления ни через один сервер VIOS."

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"Не найдена только что созданная связь элемента системы хранения %(stg_name)s "
"из сервера VIOS %(vios_name)s с разделом управления."

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "Не найдена группа томов '%(vg_name)s', необходимая для этой операции."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "Не найден кластер '%(clust_name)s', необходимый для этой операции."

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr "Не найден ни один кластер для выполнения этой операции."

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name '%(clust_name)s'."
msgstr ""
"Найдено %(clust_count)d кластеров с именем '%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d "
"Clusters found."
msgstr ""
"Не задано значение cluster_name.  Невозможно выбрать ни один из %(clust_count)d "
"найденных кластеров."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Не удалось подключить устройство хранения (ИД: %(volume_id)s) к виртуальной машине "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"Не удалось отключить том (ИД: %(volume_id)s) от виртуальной машины "
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"Не удалось выполнить предварительные шаги оперативной миграции для тома (ИД: %(volume_id)s) "
"в виртуальной машине %(instance_name)s."

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr "Сбой API PowerVM для экземпляра %(inst_name)s. %(reason)s"

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a "
"VIOS to become active for %(wait_time)d seconds.  The compute agent is not "
"able to start if no Virtual I/O Servers are available.  Please check the RMC "
"connectivity between the PowerVM NovaLink and the Virtual I/O Servers and "
"then restart the Nova Compute Agent."
msgstr ""
"Не доступен ни один сервер VIOS.  Драйвер ждал, пока какой-либо "
"VIOS станет активным, в течение %(wait_time)d с.  Вычислительный агент "
"нельзя запустить, если нет активных серверов VIOS.  Проверьте связь RMC "
"между PowerVM NovaLink и VIOS, "
"затем перезапустите вычислительный агент Nova."

#: nova_powervm/virt/powervm/exception.py:129
msgid "There are no active Virtual I/O Servers available."
msgstr "Нет ни одного активного сервера VIOS."

#: nova_powervm/virt/powervm/exception.py:133
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr "Невозможно заново скомпоновать виртуальную машину на новом хосте.  Ошибка: %(error)s"

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""
"Должен быть указан параметр %(then_opt)s, если в параметре %(if_opt)s указано "
"'%(if_value)s'."

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "Сбой оперативной миграции экземпляра '%(name)s', причина: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached on "
"the destination host %(host)s."
msgstr ""
"Не удалось выполнить миграцию %(name)s, так как том %(volume)s нельзя подключить "
"к целевому хосту %(host)s."

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s "
"concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Невозможно выполнить миграцию %(name)s, так как хост %(host)s допускает не более %(allowed)s "
"параллельных операций миграции, а в данный момент выполняется %(running)s миграций."

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Невозможно выполнить миграцию экземпляра '%(name)s', поскольку размер исходной области памяти "
"(%(source_mrs)d МБ) не совпадает с размером целевой области памяти "
"(%(target_mrs)d МБ)."

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s is "
"not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Невозможно выполнить миграцию %(name)s, так как режим совместимости процессора %(mode)s "
"отсутствует в списке режимов, поддерживаемых целевым хостом (\"%(modes)s\")."

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state is: "
"%(state)s"
msgstr ""
"Оперативная миграция экземпляра '%(name)s' не выполнена, так как она находится в состоянии "
"%(state)s"

#: nova_powervm/virt/powervm/live_migration.py:456
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"Сбой оперативной миграции экземпляра '%(name)s', поскольку подготовка не выполнена. "
"Причина: %(reason)s"

#: nova_powervm/virt/powervm/vif.py:82
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "Параметр vif_type должен присутствовать для этой реализации vif_driver"

#: nova_powervm/virt/powervm/vif.py:92
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s on "
"instance %(instance)s"
msgstr ""
"Не удалось найти драйвер VIF PowerVM для типа VIF %(vif_type)s в "
"экземпляре %(instance)s"

#: nova_powervm/virt/powervm/vif.py:655
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network '%(physnet)s' "
"for instance %(inst)s for SRIOV based VIF with MAC address %(vif_mac)s."
msgstr ""
"В физической сети '%(physnet)s' не найдены подходящие порты Ethernet "
"для экземпляра %(inst)s для VIF на основе SRIOV с MAC-адресом %(vif_mac)s."

#: nova_powervm/virt/powervm/vm.py:416
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Несколько общих пулов процессоров с именем %(pool)s."

#: nova_powervm/virt/powervm/vm.py:420
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Не удалось найти общий пул процессоров %(pool)s"

#: nova_powervm/virt/powervm/vm.py:442
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"Атрибут Flavor %(attr)s должен иметь значение True или False. Текущее значение "
"%(val)s недопустимо."

#: nova_powervm/virt/powervm/disk/driver.py:128
msgid "The configured disk driver does not support migration or resize."
msgstr "Настроенный драйвер диска не поддерживает миграцию или изменение размера."

#: nova_powervm/virt/powervm/disk/localdisk.py:293
msgid "Resizing file-backed instances is not currently supported."
msgstr "Изменение экземпляров на основе файлов пока не поддерживается."

#: nova_powervm/virt/powervm/disk/ssp.py:111
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host cluster: "
"%(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""
"Хост не является элементом того же кластера SSP. Кластер исходного хоста: "
"%(source_clust_name)s. SSP исходного хоста: %(source_ssp_name)s."

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: %(reason)s"
msgstr ""
"Не удалось сохранить NVRAM для экземпляра %(instance)s. Причина: %(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: %(reason)s"
msgstr ""
"Не удалось получить NVRAM для экземпляра %(instance)s. Причина: %(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: %(reason)s"
msgstr ""
"Невозможно удалить NVRAM для экземпляра %(instance)s. Причина: %(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr "Должен быть задан параметр конфигурации '%(option)s'."

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr "Не удалось сохранить NVRAM за %d попыток"

#: nova_powervm/virt/powervm/nvram/swift.py:267
msgid "Object does not exist in Swift."
msgstr "Объект не существует в Swift."

#: nova_powervm/virt/powervm/volume/__init__.py:62
#, python-format
msgid "Invalid connection type of %s"
msgstr "Недопустимый тип соединения %s"

#: nova_powervm/virt/powervm/volume/npiv.py:517
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""
"Не найден VIOS с картой портов NPIV для "
"сервера."

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Не удалось найти допустимый жесткий диск на серверах виртуального ввода-вывода для тома "
"%(volume_id)s."

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O Servers.  "
"Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers, but the disk "
"was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""
"Не удалось найти жесткий диск на требуемом числе серверов VIOS.  "
"Для тома %(volume_id)s требуется %(vios_req)d VIOS, однако диск "
"найден только в %(vios_act)d VIOS."

# ENGL1SH_VERS10N 49196_14 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 28
# T9N_SH1P_STR1NG VC140AAP001 2
