# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 5.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-10-03 04:15-0400\n"
"PO-Revision-Date: 2017-10-03 04:15-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.1\n"
"Language: en_US\n"
"Plural-Forms: nplurals=1; plural=0;"

#: nova_powervm/virt/powervm/driver.py:211
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "期望刚好找到一个主机；但是找到 %d 个主机"

#: nova_powervm/virt/powervm/driver.py:1002
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "插入 VIF 失败，因为找不到实例 %s。"

#: nova_powervm/virt/powervm/driver.py:1007
msgid "Plug vif failed because of an unexpected error."
msgstr "插入 VIF 失败，因为发生了意外错误。"

#: nova_powervm/virt/powervm/driver.py:1097
msgid "Cannot reduce disk size."
msgstr "无法减小磁盘大小。"

#: nova_powervm/virt/powervm/driver.py:1111
#: nova_powervm/virt/powervm/driver.py:1219
msgid "Cannot migrate local disks."
msgstr "无法迁移本地磁盘。"

#: nova_powervm/virt/powervm/driver.py:1740
msgid "Unable to open console."
msgstr "无法打开控制台。"

#: nova_powervm/virt/powervm/exception.py:38
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual optical "
"media within.  Unable to create the media repository."
msgstr ""
"找不到用于存储虚拟光学介质的卷组 %(vol_grp)s。"
"无法创建介质存储库。"

#: nova_powervm/virt/powervm/exception.py:45
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with UDID "
"%(udid)s failed to appear after %(polls)d polls over %(timeout)d seconds."
msgstr ""
"已在管理分区上扫描 SCSI 总线 %(bus)x，UDID 为"
"未能在 %(polls)d 轮询超过 %(timeout)d 秒后检测到 %(udid)s 的磁盘。"

#: nova_powervm/virt/powervm/exception.py:52
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"期望以下位置的管理分区中找到正好一个磁盘："
"%(path_pattern)s；但发现 %(count)d 个磁盘。"

#: nova_powervm/virt/powervm/exception.py:58
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d seconds."
msgstr ""
"尝试删除设备 %(devpath)s 之后，"
"该设备仍然存在管理分区上。已在 %(timeout)d 秒钟之内轮询了 %(polls)d 次。"

#: nova_powervm/virt/powervm/exception.py:64
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"无法将实例 %(instance_name)s 的引导磁盘映射至任何"
"Virtual I/O Server 中的管理分区。"

#: nova_powervm/virt/powervm/exception.py:70
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"找不到存储器元素 %(stg_name)s 的新创建的从 Virtual I/O Server %(vios_name)s"
"至管理分区的映射。"

#: nova_powervm/virt/powervm/exception.py:76
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr "找不到对应此操作的卷组“%(vg_name)s”。"

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr "找不到对应此操作的集群“%(clust_name)s”。"

#: nova_powervm/virt/powervm/exception.py:86
msgid "Unable to locate any Cluster for this operation."
msgstr "找不到对应此操作的任何集群。"

#: nova_powervm/virt/powervm/exception.py:90
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name '%(clust_name)s'."
msgstr ""
"意外发现与名称“%(clust_name)s”相匹配的 %(clust_count)d 个集群。"

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d "
"Clusters found."
msgstr ""
"未指定 cluster_name。拒绝选择所发现的 %(clust_count)d 个"
"集群中的一个。"

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"无法将存储器（标识：%(volume_id)s）连接至虚拟机"
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"无法将卷（标识：%(volume_id)s）从虚拟机"
"%(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"无法从虚拟机 %(instance_name)s 对卷（标识：%(volume_id)s）"
"执行预先实时迁移步骤。"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid "PowerVM API failed to complete for instance=%(inst_name)s.%(reason)s"
msgstr "未能对实例 %(inst_name)s 完成 PowerVM API。原因：%(reason)s"

#: nova_powervm/virt/powervm/exception.py:120
#, python-format
msgid ""
"No Virtual I/O Servers are available.  The driver attempted to wait for a "
"VIOS to become active for %(wait_time)d seconds.  The compute agent is not "
"able to start if no Virtual I/O Servers are available.  Please check the RMC "
"connectivity between the PowerVM NovaLink and the Virtual I/O Servers and "
"then restart the Nova Compute Agent."
msgstr ""
"没有可用 Virtual I/O Server。驱动程序尝试等待"
"%(wait_time)d 秒以使 VIOS 变为活动状态。如果没有可用 Virtual I/O Server，"
"那么计算代理程序无法启动。请检查"
"PowerVM NovaLink 与 Virtual I/O Server 之间的 RMC 连接，"
"然后重新启动 Nova 计算代理程序。"

#: nova_powervm/virt/powervm/exception.py:129
msgid "There are no active Virtual I/O Servers available."
msgstr "没有活动可用 Virtual I/O Server。"

#: nova_powervm/virt/powervm/exception.py:133
#, python-format
msgid "Unable to rebuild virtual machine on new host.  Error is %(error)s"
msgstr "无法在新主机上重建虚拟机。错误为 %(error)s"

#: nova_powervm/virt/powervm/exception.py:138
#, python-format
msgid ""
"The %(then_opt)s option is required if %(if_opt)s is specified as "
"'%(if_value)s'."
msgstr ""
"如果 %(if_opt)s 指定为“%(if_value)s”，"
"那么必须指定 %(then_opt)s 选项。"

#: nova_powervm/virt/powervm/live_migration.py:44
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "实时迁移实例“%(name)s”失败，原因：%(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:49
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached on "
"the destination host %(host)s."
msgstr ""
"无法迁移 %(name)s，因为卷 %(volume)s 无法在"
"目标主机 %(host)s 上连接。"

#: nova_powervm/virt/powervm/live_migration.py:59
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s "
"concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"无法迁移 %(name)s，因为主机 %(host)s 仅允许 %(allowed)s "
"个并行迁移，但是有 %(running)s 个迁移当前正在运行。"

#: nova_powervm/virt/powervm/live_migration.py:109
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"无法迁移实例“%(name)s”，"
"因为源的内存区域大小 (%(source_mrs)d MB)"
"与目标的内存区域大小 (%(target_mrs)d MB) 不匹配。"

#: nova_powervm/virt/powervm/live_migration.py:279
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s is "
"not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"无法迁移 %(name)s，因为其处理器兼容性方式 %(mode)s"
"不在目标主机支持的方式列表“%(modes)s”中。"

#: nova_powervm/virt/powervm/live_migration.py:294
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state is: "
"%(state)s"
msgstr ""
"实例“%(name)s”的实时迁移失败，因为迁移状态为："
"%(state)s"

#: nova_powervm/virt/powervm/live_migration.py:456
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"实时迁移实例“%(name)s”失败，因为它未就绪。"
"原因：%(reason)s"

#: nova_powervm/virt/powervm/vif.py:82
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "对于此 vif_driver 实现，必须存在 vif_type 参数"

#: nova_powervm/virt/powervm/vif.py:92
#, python-format
msgid ""
"Unable to find appropriate PowerVM VIF Driver for VIF type %(vif_type)s on "
"instance %(instance)s"
msgstr ""
"在实例 %(instance)s 上找不到对应 VIF 类型 %(vif_type)s 的相应 PowerVM VIF"
"驱动程序。"

#: nova_powervm/virt/powervm/vif.py:655
#, python-format
msgid ""
"Unable to find acceptable Ethernet ports on physical network '%(physnet)s' "
"for instance %(inst)s for SRIOV based VIF with MAC address %(vif_mac)s."
msgstr ""
"对于具有 MAC 地址 %(vif_mac)s 的基于 SRIOV 的 VIF 的实例 %(inst)s，"
"在物理网络“%(physnet)s”上找不到可接受的以太网端口。"

#: nova_powervm/virt/powervm/vm.py:416
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "存在多个名称为 %(pool)s 的共享处理池。"

#: nova_powervm/virt/powervm/vm.py:420
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "找不到共享处理池 %(pool)s"

#: nova_powervm/virt/powervm/vm.py:442
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"flavor 属性 %(attr)s 必须为 True 或 False。"
"不允许使用当前值 %(val)s。"

#: nova_powervm/virt/powervm/disk/driver.py:128
msgid "The configured disk driver does not support migration or resize."
msgstr "所配置的磁盘驱动程序不支持迁移或调整大小。"

#: nova_powervm/virt/powervm/disk/localdisk.py:293
msgid "Resizing file-backed instances is not currently supported."
msgstr "当前不支持调整文件备份实例的大小。"

#: nova_powervm/virt/powervm/disk/ssp.py:111
#, python-format
msgid ""
"The host is not a member of the same SSP cluster. The source host cluster: "
"%(source_clust_name)s. The source host SSP: %(source_ssp_name)s."
msgstr ""
"该主机不是相同 SSP 集群的成员。源主机集群："
"%(source_clust_name)s. 源主机 SSP：%(source_ssp_name)s。"

#: nova_powervm/virt/powervm/nvram/api.py:25
#, python-format
msgid ""
"The NVRAM could not be stored for instance %(instance)s. Reason: %(reason)s"
msgstr ""
"无法存储实例 %(instance)s 的 NVRAM。原因：%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:30
#, python-format
msgid ""
"The NVRAM could not be fetched for instance %(instance)s. Reason: %(reason)s"
msgstr ""
"无法访存实例 %(instance)s 的 NVRAM。原因：%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:35
#, python-format
msgid ""
"The NVRAM could not be deleted for instance %(instance)s. Reason: %(reason)s"
msgstr ""
"无法删除实例 %(instance)s 的 NVRAM。原因：%(reason)s"

#: nova_powervm/virt/powervm/nvram/api.py:40
#, python-format
msgid "The configuration option '%(option)s' must be set."
msgstr "必须设置配置选项“%(option)s”。"

#: nova_powervm/virt/powervm/nvram/swift.py:195
#, python-format
msgid "Unable to store NVRAM after %d attempts"
msgstr "尝试 %d 次之后仍然无法存储 NVRAM"

#: nova_powervm/virt/powervm/nvram/swift.py:267
msgid "Object does not exist in Swift."
msgstr "Swift 中没有对象。"

#: nova_powervm/virt/powervm/volume/__init__.py:62
#, python-format
msgid "Invalid connection type of %s"
msgstr "%s 的连接类型无效"

#: nova_powervm/virt/powervm/volume/npiv.py:517
msgid ""
"Unable to find a Virtual I/O Server that hosts the NPIV port map for the "
"server."
msgstr ""
"找不到用来管理服务器的 NPIV 端口映射的"
"Virtual I/O Server。"

#: nova_powervm/virt/powervm/volume/volume.py:117
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"未能在任何 Virtual I/O Server 上发现卷的有效 hdisk"
"%(volume_id)s."

#: nova_powervm/virt/powervm/volume/volume.py:121
#, python-format
msgid ""
"Failed to discover the hdisk on the required number of Virtual I/O Servers.  "
"Volume %(volume_id)s required %(vios_req)d Virtual I/O Servers, but the disk "
"was only found on %(vios_act)d Virtual I/O Servers."
msgstr ""
"在所需数目的 Virtual I/O Server 上，未能发现 hdisk。"
"卷 %(volume_id)s 需要 %(vios_req)d 个 Virtual I/O Server，但仅在"
"%(vios_act)d 个 Virtual I/O Server 上发现该磁盘。"

# ENGL1SH_VERS10N 49196_14 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 28
# T9N_SH1P_STR1NG VC140AAP001 2
